version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgresql_pocs
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root  
    ports:
      - 5432:5432
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql